from selenium.webdriver.common.by import By

class AccountPageLocators:
    PROFILE_MENU = (By.CSS_SELECTOR, 'a[href="/account/profile"]')
    AVATAR_INPUT = (By.CSS_SELECTOR, 'div.mantine-Avatar-root')
    NAME_INPUT = (By.CSS_SELECTOR, 'input[id^="mantine-"][data-path="name"]')
    PHONE_INPUT = (By.CSS_SELECTOR, 'input[id^="mantine-"][data-path="phone"]')
    EMAIL_INPUT = (By.CSS_SELECTOR, 'input[id^="mantine-"][data-path="email"]')
    ADDRESS_INPUT = (By.CSS_SELECTOR, 'textarea[id^="mantine-"][data-path="address"]')
    SUBMIT_BUTTON = (By.XPATH, '//button[.//span[text()="Simpan"]]')
    BACK_BUTTON = (By.CSS_SELECTOR, 'button .tabler-icon-arrow-left')
    CATEGORY_MENU = (By.CSS_SELECTOR, 'a[href="/account/categories"]')
    CATEGORY_LABEL_FIRST = (By.CSS_SELECTOR, 'label[for="01jkacy7rcyq4sg9bn5059p4wk"]')
    CATEGORY_LABEL_SECOND = (By.CSS_SELECTOR, 'label[for="01jkacy7s04jxq4ft0g5p1a3ew"]')
    GOALS_MENU = (By.CSS_SELECTOR, 'a[href="/account/goals"]')
    GOALS_LABEL_FIRST = (By.CSS_SELECTOR, 'label[for="01jkacy809jthf7qnq9fn282fn"]')
    GOALS_LABEL_SECOND = (By.CSS_SELECTOR, 'label[for="01jkacy81m22y6wpw9knnjxy3d"]')
    ABOUT_MENU = (By.CSS_SELECTOR, 'a[href="/pages/tentang-sobatlazismu"]')
    TERMS_MENU = (By.CSS_SELECTOR, 'a[href="/pages/syarat-ketentuan"]')
    PRIVACY_MENU = (By.CSS_SELECTOR, 'a[href="/pages/kebijakan-privasi"]')
    HELP_MENU = (By.CSS_SELECTOR, 'a[href="/pages/bantuan"]')
    ACCOUNT_BACK_BUTTON = (By.CSS_SELECTOR, 'a[href="/account"]')
    LOGOUT_BUTTON = (By.XPATH, '//button[.//p[text()="Keluar"]]')
    CANCEL_CONFIRM_BUTTON = (By.XPATH, '//button[.//span[text()="Batal"]]')
    LOGOUT_CONFIRM_BUTTON = (By.XPATH, '//button[.//span[text()="Keluar"]]')